
<?php $this->headTitle($this->title); ?>

<div class="hero-unit">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>
    <p><?php echo $this->escapeHtml($this->content); ?></p>
</div>



<!--Example content, a nested grid layout that could be used within the content-->
<div class="row">
    <div class="span4 bgd-blue">
        <div class="row">
            <div class="span1 bgd-green">1</div>
            <div class="span3 bgd-green">3</div>  
        </div>
    </div>
    <div class="span4 bgd-blue">4</div>
    <div class="span4 bgd-blue">4</div>
</div>

<!--Example content, a nested grid layout that could be used within the content-->
<div class="row">    
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
    <div class="span1 bgd-red">1</div>
</div>

<div class="row">
    <div class="span2 offset1 bgd-blue">2 (offset 1)</div>
    <div class="span2 offset1 bgd-blue">2 (offset 1)</div>
    <div class="span2 offset1 bgd-blue">2 (offset 1)</div>
    <div class="span2 offset1 bgd-blue">2 (offset 1)</div>
</div>

            
	
