<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Prepended '. $this->translate('Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') */?>
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        
        <!-- Nav bar -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a href="<?php echo $this->url('home') ?>" class="brand">Backend - <?php echo $this->translate('Brand') ?></a>
                    <div class="nav-collapse collapse">
                        <?php if ($this->identity()):                            
                            echo $this->navigation('admin_navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav')
                                ->render();
                        ?>               
                        <div class="btn-group pull-right">
                            <a class="btn dropdown-toggle btn-inverse user-indentity" data-toggle="dropdown" href="#">
                                <i class="icon-user icon-white"></i>&nbsp;<?php echo $this->escapeHtml($this->identity()->getUsername()); ?>&nbsp;<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">  
                                <li><a href="<?php echo $this->url('admin/user', array('action' => 'edit','id'=>$this->identity()->getId())); ?>"><i class="icon-user"></i> Edit</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('admin/logout', array()); ?>"><i class="icon-lock"></i></i> Logout</a></li>
                            </ul>
                        </div>
                        <?php endif; ?>           
                    </div>
                </div>
            </div>
        </div>
        
        
        
        <div class="main-content container">
     
            <?php
   
            
            $ourView = current($this->viewModel()->getCurrent()->getChildren());

            if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
                
                    <?php foreach ($ourView->flashMessages as $message) : ?>

                        <div class="main-message alert <?php echo is_array($message) ? key($message) : ''; ?>">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <!--h4><?php echo is_array($message) ? strtolower(str_replace('alert-', '', key($message))) : 'alert';?>!</h4-->
                            <?php echo is_array($message) ? current($message) : $message; ?>
                        </div>
                    
                    <?php endforeach; ?>
            
            <?php endif; ?>
            
            
            <?php echo $this->content; ?>            
                     
            
        </div> <!-- /container -->
        
        
        <?php echo $this->inlineScript() ?>
        
        
    </body>
</html>
