

<?php $this->headTitle($this->title); ?>


<div class="row">
           
    <div class="span8 pull-left">
        <h4><?php echo $this->escapeHtml($this->title); ?></h4>
        <h5>
            <span class="icon-list"></span> 
            <?php 
                echo (1==($count = $this->paginator->getTotalItemCount())) ? $count.' album' : $count.' albums'; 
            ?>            
        </h5>
    </div>
    
    
    <div class="span4 pull-right">
        <div class="pagination pagination-right">
            <?php // add at the end of the file after the table
            echo $this->paginationControl(
                // the paginator admin
                $this->paginator,
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'Album'),
                // the route to link to when a user clicks a control link
                array(
                    'route' => 'admin/album'
                )
            );
            ?>
        </div>
    </div>


    <div class="content span12">

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Title</th>
                <th>Artist</th>
                <th>Created</th>
                <th>Comments</th>
                <th><a href="<?php echo $this->url('admin/album', array('action'=>'add'));?>" class="btn btn-mini pull-right"><i class="icon-plus"></i></a></th>
            </tr>
            <?php foreach ($this->paginator as $album) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($album->title);?></td>
                    <td><?php echo $this->escapeHtml($album->artist);?></td>
                    <td><?php echo $this->escapeHtml($album->created);?></td>
                    <td>
                        <?php
                        if ($comments = $album->getComments()) {
                            foreach($comments AS $comment) : ?>
                                <p>
                                    <div class="btn-group pull-right">                                
                                        <a href="<?php echo $this->url('admin/comment',array('action'=>'edit', 'id' => $comment->id));?>" class="btn btn-mini">
                                            <i class="icon-pencil"></i>
                                        </a>
                                        <a href="<?php echo $this->url('admin/comment',array('action'=>'delete', 'id' => $comment->id));?>" class="btn btn-mini">
                                            <i class="icon-trash"></i>
                                        </a>
                                    </div>
                                    <strong><?php echo $comment->message; ?></strong> <small>by <?php echo $comment->author; ?> (<?php echo $comment->email; ?>) <em><?php echo $comment->dated; ?></em></small>
                                </p>
                            <?php     
                            endforeach;                 }
                        ?>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url('admin/comment',array('action'=>'add', 'id' => $album->id));?>" class="btn"><i class="icon-comment"></i></a>
                            <a href="<?php echo $this->url('admin/album',array('action'=>'edit', 'id' => $album->id));?>" class="btn"><i class="icon-pencil"></i></a>
                            <a href="<?php echo $this->url('admin/album',array('action'=>'delete', 'id' => $album->id));?>" class="btn"><i class="icon-trash"></i></a> 
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        
    </div>
    
    
</div>