
<?php $this->headTitle($this->title); ?>


<h1><?php echo $this->escapeHtml($this->title); ?></h1>



    <!--Example content, a nested grid layout that could be used within the content-->
    <div class="row">
        <div class="span4 bgd-red">
            <div class="row">
                <div class="span1 bgd-green">green</div>
                <div class="span3 bgd-green">green</div>  
            </div>
        </div>
        <div class="span4 bgd-red">red</div>
        <div class="span4 bgd-blue">blue</div>
    </div>


            
	
