
<?php

$title = 'Secure Area';
$this->headTitle($title);
?>

<div class="row">

    <div class="span6 well well-large">
        
        <h3><?php echo $this->escapeHtml($title); ?></h3>

        <?php
        $form = $this->form->prepare();
        $form->get('submit')->setAttribute('class', 'btn-large btn-inverse');
        echo $this->formTwb($form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL);
        ?>
        
    </div>
    
</div>


