
<div class="hero-unit title">
    <h4>Json test</h4>
    Use firebug to see the response
    <h5>Url: <span id="url">/rest</span></h5>
    Update & get, can fail because the the server responds with an error, this is because the id used is random and it is not always found on the server
</div>

<div class="row">

    <div class="span2">
        <div class="btn-group btn-group-vertical">        
            <button class="btn list btn-inverse">List /</button>
            <button class="btn get btn-inverse">Get / ID</button> 
            <button class="btn post btn-inverse">Create / POST</button>
            <button class="btn put btn-inverse">Update / PUT</button>
            <button class="btn delete btn-danger">Delete / DELETE</button>
        </div>     
    </div>
        
    <div class="span10">
        <pre class="output" style="height:150px;"></pre>
    </div>
        
</div>



<script type="text/javascript">


    var url = $('#url').text();
    var outputElem = $('pre.output');
    var listElem = $('.list');  
    var getElem = $('.get');  
    var postElem = $('.post');  
    var putElem = $('.put');  
    var deleteElem = $('.delete');  
    
    // random vars
    var ids = [<?php echo implode(',', $this->test_ids); ?>];
    var artists = ['Artist1','Artist2','Artist3','Artist4'];
    var titles = ['Title1','Title2','Title3','Title4'];
 

    $().ready(function(){
        
        // demo list interaction
        listElem.click(function(){
            
            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    outputElem.text('List: ' + JSON.stringify(response.data)); 
                }
            });
            
        });
        
        
        // get interaction
        getElem.click(function(){
            
            var random_id = ids[Math.floor(Math.random()*ids.length)];
                        
            $.ajax({
                url: url + '/' + random_id,
                type: 'GET',
                success: function(response) {
                    outputElem.text('Get: ' + JSON.stringify(response.data)); 
                },
                error: function(jqXHR, textStatus, error){
                    outputElem.text('Failed: ' + error); 
                }
            });
            
        });
        
        
        // post (add) interaction
        postElem.click(function(){
            
            var random_artist = artists[Math.floor(Math.random()*artists.length)];
            var random_title = titles[Math.floor(Math.random()*titles.length)];
             
            $.ajax({
                url: url,
                type: 'POST',
                data: {artist:random_artist,title:random_title},
                success: function(response) {
                    outputElem.text('Added: ' + JSON.stringify(response.data));                    
                }
            });
            
            
        });
        
        
        // put (update) interaction
        putElem.click(function(){
            
            var random_id = ids[Math.floor(Math.random()*ids.length)];
            var random_artist = artists[Math.floor(Math.random()*artists.length)];
            var random_title = titles[Math.floor(Math.random()*titles.length)];
            
            $.ajax({
                url: url + "/" + random_id,
                type: 'PUT',
                data: {artist:random_artist,title:random_title},
                success: function(response) {
                    outputElem.text('Updated: ' + JSON.stringify(response.data)); 
                },
                error: function(jqXHR, textStatus, error){
                    outputElem.text('Failed: ' + error); 
                }
            });
           
            
        });
        
      
        // delete interaction
        deleteElem.click(function(){
            
            var random_id = ids[Math.floor(Math.random()*ids.length)];
            
            $.ajax({
                url: url + "/" + random_id,
                type: 'DELETE',
                success: function(response) {
                    outputElem.text('Deleted: ' + JSON.stringify(response.data)); 
                }
            });

        });
      
    });

</script>


