

<div class="dates height-fill height-fill-locked row height-hidden">

    
    <!-- Header -->
    <div class="dates-header span12">
        <div class="row">
            
            <div class="span1">
                <button class="btn btn-block">Date</button>
            </div>
            
            <div class="span2">
                <button class="btn btn-block">Balance</button>
            </div>

            <div class="btn-group span9">
                <a href="#" class="btn dropdown-toggle btn-block" data-toggle="dropdown">
                    &pound;321.53 on Saturday 1st of May 2013&nbsp;<span class="caret"></span>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li><a href="#myModal" role="button" data-toggle="modal"><i class="icon-pencil"></i> Add Transaction</a></li>
                    <li><a href="#myModal" role="button" data-toggle="modal"><i class="icon-remove"></i> Change Date</a></li>
                </ul>
            </div>
                
            
        </div>
    </div>
    <!-- Header -->
    


    <!-- Content -->
    <div class="dates-content span12 height-fill-locked height-scroll">
        <?php foreach($this->dates AS $dateKey=>$dateVal) : ?>
            
            <!-- date -->
            <div class="date <?php if ($this->todayKey==$dateKey) echo 'current'; ?> row">
                
                <!-- Date -->
                <div class='date-title span1'>
                    <?php echo date('jS M',$dateVal->unix); ?>
                </div>

                <!-- Balance -->
                <div class="date-balance span2 <?php echo $dateVal->balance==0 ? 'neutral' : $dateVal->balance>0 ? 'positive' : 'negative'; ?>">
                    &pound; <?php echo $dateVal->balance; ?>
                </div>                
                
                <div class="date-transactions span9-scrollable" >
                        

                    <ul id="<?php echo $dateKey; ?>" class="inline">

                        <?php foreach ($dateVal->transactions AS $transKey=>$transVal) : ?>

                            <li 
                                id="<?php echo $transKey; ?>" 
                                class="date-transaction <?php echo $transVal->amount>0 ? 'positive' : 'negative'; ?> span4"
                                >                                
                                <input type="text" placeholder="&pound;<?php echo $transVal->amount; ?>" class="span2"> 
                                <input type="text" placeholder="<?php echo $transVal->type; ?>" class="span2"> 
                                <a href="" class="pull-right">x</a>
                            </li>
                            
                        <?php endforeach; ?>
                    </ul> 
                    
                    
                </div>

            </div>
        <?php endforeach; ?> 
    </div>
    <!-- Content -->
    
    
</div>




<script type='text/javascript'>
    
    $(function() {

        $(".date-transactions ul").sortable({
            connectWith: ".date-transactions ul",
            opacity: 0.6, 
            cursor: 'move',
            update : function(e, ui) {
                var id = ui.item.attr('id');
                var to = $(this).attr('id');
                console.log('id: ' + id + ' to: ' + to);
                console.log('order: ')
                console.log($(this).children());
            }

        });

    });
</script>



