
<div class="hero-unit">
    <h3>Json test</h3>
</div>

<div class="row">

    <div class="span6">
        <div class="btn-group">        
            <button class="btn list">List /</button>
            <button class="btn get">Get / ID</button> 
            <button class="btn post">Create / POST</button>
            <button class="btn put">Update / PUT</button>
            <button class="btn delete">Delete / DELETE</button>
        </div>     
    </div>
        
    <div class="span6">
        <pre class="output" style="height:300px;"></pre>
    </div>
        
</div>



<script type="text/javascript">


    var url = "/rest";
    var outputElem = $('pre.output');
    var listElem = $('.list');  
    var getElem = $('.get');  
    var postElem = $('.post');  
    var putElem = $('.put');  
    var deleteElem = $('.delete');  
    
    // random vars
    var ids = [10,11,12,13,14,15,16,17,18,19,20];
    var artists = ['Artist1','Artist2','Artist3','Artist4'];
    var titles = ['Title1','Title2','Title3','Title4'];
 

    $().ready(function(){
        
        
        // demo list interaction
        listElem.click(function(){
            
            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    outputElem.text('Length: ' + response.data.length); 
                }
            });
            
        });
        
        
        // get interaction
        getElem.click(function(){
            
            var random_id = ids[Math.floor(Math.random()*ids.length)];
                        
            $.ajax({
                url: url + '/' + random_id,
                type: 'GET',
                success: function(response) {
                    outputElem.text('Getting ' + response.data); 
                }
            });
            
        });
        
        
        // post (add) interaction
        postElem.click(function(){
            
            var random_artist = artists[Math.floor(Math.random()*artists.length)];
            var random_title = titles[Math.floor(Math.random()*titles.length)];
             
            $.ajax({
                url: url,
                type: 'POST',
                data: {artist:random_artist,title:random_title},
                success: function(response) {
                    outputElem.text('Added'); 
                }
            });
            
            
        });
        
        
        // put (update) interaction
        putElem.click(function(){
            
            var random_id = ids[Math.floor(Math.random()*ids.length)];
            var random_artist = artists[Math.floor(Math.random()*artists.length)];
            var random_title = titles[Math.floor(Math.random()*titles.length)];
            
            $.ajax({
                url: url + "/" + random_id,
                type: 'PUT',
                data: {artist:random_artist,title:random_title},
                success: function(response) {
                    outputElem.text('Updated'); 
                }
            });
           
            
        });
        
      
        // delete interaction
        deleteElem.click(function(){
            
            var random_id = ids[Math.floor(Math.random()*ids.length)];
            
            $.ajax({
                url: url + "/" + random_id,
                type: 'DELETE',
                success: function(response) {
                    outputElem.text('deleted'); 
                }
            });

        });
      
    });

</script>


