


<?php $this->headTitle($this->title); ?>



<div class="row">
           
    <div class="span8 pull-left">
        <h4><?php echo $this->escapeHtml($this->title); ?></h4>
        <h5>
            <span class="icon-list"></span> 
            <?php 
                echo (1==($count = $this->paginator->getTotalItemCount())) ? $count.' comment' : $count.' comments'; 
            ?>            
        </h5>
    </div>


    <div class="span4 pull-right">
        <div class="pagination pagination-right">
            <?php // add at the end of the file after the table
            echo $this->paginationControl(
                // the paginator admin
                $this->paginator,
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'Album'),
                // the route to link to when a user clicks a control link
                array(
                    'route' => 'admin/comment'
                )
            );
            ?>
        </div>
    </div>


    <div class="content span12">

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Album</th>
                <th>Message</th>
                <th>Author</th>
                <th>Email</th>
                <th>Dated</th>
                <th><a href="<?php echo $this->url('admin/comment', array('action'=>'add'));?>" class="btn btn-mini pull-right"><i class="icon-plus"></i></a></th>
            </tr>
            <?php foreach ($this->paginator as $comment) : ?>
                <tr <?php echo !$comment->getAlbum() ? 'class="error"' : ''; ?>>
                    <td><?php echo $comment->getAlbum() ? $this->escapeHtml($comment->getAlbum()->title) : '<span class="label label-important"><i class="icon-exclamation-sign icon-white"></i> Orphaned!</span>';?></td>
                    <td><?php echo $this->escapeHtml($comment->message);?></td>
                    <td><?php echo $this->escapeHtml($comment->author);?></td>
                    <td><?php echo $this->escapeHtml($comment->email);?></td>
                    <td><?php echo $this->escapeHtml($comment->dated);?></td>            
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url('admin/comment',array('action'=>'edit', 'id' => $comment->id));?>" class="btn"><i class="icon-pencil"></i></a>
                            <a href="<?php echo $this->url('admin/comment',array('action'=>'delete', 'id' => $comment->id));?>" class="btn"><i class="icon-trash"></i></a> 
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    
</div>
