


<?php $this->headTitle($this->title); ?>

<h1><?php echo $this->escapeHtml($this->title); ?></h1>


<div class="row">

    <div class="span10">
        <?php // add at the end of the file after the table
        echo $this->paginationControl(
            // the paginator admin
            $this->paginator,
            'sliding',
            // the partial to use to render the control
            array('partial/paginator.phtml', 'Comment'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'admin/comment'
            )
        );
        ?>
    </div>
    
        
    <div class="span2">
        <a href="<?php echo $this->url('admin/comment', array('action'=>'add'));?>" class="btn btn-large pull-right"><i class="icon-plus"></i></a>
    </div>
</div>
	
<table class="table table-striped table-hover">
    <tr>
        <th>Album</th>
        <th>Message</th>
        <th>Author</th>
        <th>Email</th>
        <th>Dated</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $comment) : ?>
        <tr>
            <td><?php echo $comment->getAlbum() ? $this->escapeHtml($comment->getAlbum()->title) : 'None';?></td>
            <td><?php echo $this->escapeHtml($comment->message);?></td>
            <td><?php echo $this->escapeHtml($comment->author);?></td>
            <td><?php echo $this->escapeHtml($comment->email);?></td>
            <td><?php echo $this->escapeHtml($comment->dated);?></td>            
            <td>
                <div class="btn-group pull-right">
                    <a href="<?php echo $this->url('admin/comment',array('action'=>'edit', 'id' => $comment->id));?>" class="btn"><i class="icon-pencil"></i></a>
                    <a href="<?php echo $this->url('admin/comment',array('action'=>'delete', 'id' => $comment->id));?>" class="btn"><i class="icon-trash"></i></a> 
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>